// AUTO-GENERATED by scripts/gen-locales.mjs — do not edit by hand.
//
// Mirrors OneEntry → Settings → Localization (active locales, admin order).
// Regenerated on `npm run dev` / `npm run build`; committed so a build without
// CMS access still routes the languages that shipped last.
//
// The default locale is NOT here — see `DEFAULT_LOCALE` in ./locale.ts.

/** Active OE locale codes as configured in the project, in admin-panel order. */
export const GENERATED_CMS_LOCALES: readonly string[] = ['de_DE', 'en_US'];
