#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * scripts/build-oedata.mjs (session v2, Wave 7.3)
 * --------------------------------------------------
 * Materializer for the OEdata mock dataset.
 *
 * Reads:
 *   - .oedata-workspace/OEdata.draft.json                    (master)
 *   - .oedata-workspace/OEdata.draft.<domain>.json           (12 partials)
 *   - src/app/data/{women,men}-{clothing,bags,shoes,accessories}.ts (rich product source)
 *
 * Writes:
 *   - src/app/OEdata/*.ts                                    (one file per domain)
 *   - src/app/OEdata/README.md                               (provenance)
 *
 * The script is fully deterministic — re-running it produces byte-identical
 * output (idempotent). It does NOT touch any project source.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build as esbuild } from 'esbuild';

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const WORKSPACE = resolve(REPO_ROOT, '.oedata-workspace');
const DATA_DIR = resolve(REPO_ROOT, 'src/app/data');
const OUT_DIR = resolve(REPO_ROOT, 'src/app/OEdata');

const REPRO_HASH =
  '6e29ff95c01f4cc0cd5b1c0485540d90d2d7631a922c1d3c4103eff1b9e8b710';

const BANNER = [
  '// Auto-generated by scripts/build-oedata.mjs (session v2).',
  `// Source: .oedata-workspace/OEdata.draft*.json (reproducibility_hash ${REPRO_HASH.slice(0, 8)}...).`,
  '// DO NOT EDIT BY HAND — regenerate via: node scripts/build-oedata.mjs',
  '',
  '',
].join('\n');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const richText = (plain) => ({
  htmlValue: `<p>${escapeHtml(plain).replace(/\n/g, '<br/>')}</p>`,
  plainValue: String(plain ?? ''),
  mdValue: String(plain ?? ''),
  params: {},
});

const slugify = (s) =>
  String(s ?? '')
    .toLowerCase()
    .trim()
    .replace(/&/g, 'and')
    .replace(/['’`]/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

const basenameFromUrl = (url, fallback = 'image.jpg') => {
  try {
    const u = new URL(url);
    const last = u.pathname.split('/').filter(Boolean).pop();
    return last || fallback;
  } catch {
    if (typeof url !== 'string') return fallback;
    const last = url.split('/').filter(Boolean).pop();
    return last || fallback;
  }
};

const imageObject = (url, params = {}) => ({
  filename: basenameFromUrl(url),
  downloadLink: url,
  previewLink: url,
  size: null,
  params,
});

// Stable JSON.stringify — sorts object keys recursively to make output reproducible.
const stableStringify = (value, indent = 2) => {
  const seen = new WeakSet();
  const sort = (v) => {
    if (v === null || typeof v !== 'object') return v;
    if (seen.has(v)) return undefined;
    seen.add(v);
    if (Array.isArray(v)) return v.map(sort);
    const out = {};
    for (const k of Object.keys(v)) out[k] = sort(v[k]);
    return out;
  };
  return JSON.stringify(sort(value), null, indent);
};

const writeTs = (filename, exportsMap, header = '') => {
  const lines = [BANNER];
  if (header) lines.push(header, '');
  for (const [name, value] of Object.entries(exportsMap)) {
    if (typeof value === 'string') {
      // Pre-rendered TS expression.
      lines.push(`export const ${name} = ${value} as const;`, '');
    } else {
      lines.push(
        `export const ${name} = ${stableStringify(value, 2)} as const;`,
        '',
      );
    }
  }
  writeFileSync(join(OUT_DIR, filename), lines.join('\n'), 'utf8');
};

const HEX_TO_COLOR_SLUG = new Map([
  ['#000000', 'black'],
  ['#ffffff', 'white'],
  ['#808080', 'gray'],
  ['#a0a0a0', 'gray'],
  ['#36454f', 'charcoal'],
  ['#1b3a5c', 'navy'],
  ['#000080', 'navy'],
  ['#001f3f', 'navy'],
  ['#800020', 'burgundy'],
  ['#8b0000', 'dark_red'],
  ['#c4a882', 'camel'],
  ['#5c3a1e', 'brown'],
  ['#5d4037', 'brown'],
  ['#4a2c2a', 'brown'],
  ['#f5deb3', 'beige'],
  ['#f8d7be', 'beige'],
  ['#f88a8a', 'pink'],
  ['#ffb6c1', 'pink'],
  ['#ffc0cb', 'pink'],
  ['#da1e1e', 'red'],
  ['#ff0000', 'red'],
  ['#ff6b6b', 'coral_red'],
  ['#808000', 'khaki'],
  ['#556b2f', 'olive_green'],
  ['#4169e1', 'royal_blue'],
  ['#2e8b57', 'sea_green'],
  ['#c0c0c0', 'silver'],
  ['#d4af37', 'gold'],
  ['#4a0000', 'dark_red'],
  ['#a0522d', 'sienna'],
  ['#ffe4e1', 'mint'],
  ['#f5f0e8', 'cream'],
]);
const hexToSlug = (hex) => {
  if (typeof hex !== 'string') return null;
  const k = hex.toLowerCase();
  return HEX_TO_COLOR_SLUG.get(k) ?? k.replace('#', 'hex_');
};

const isClothingLetterSize = (s) =>
  /^(xxxs|xxs|xs|s|m|l|xl|xxl|xxxl|one_size|onesize)$/i.test(String(s));
const isShoeNumericSize = (s) => /^[0-9]{2,3}(\.5)?$/.test(String(s));

// ---------------------------------------------------------------------------
// Step 1: read every workspace partial.
// ---------------------------------------------------------------------------

console.log('[oedata] reading workspace…');

const master = readJson(join(WORKSPACE, 'OEdata.draft.json'));
const productsPartial = readJson(join(WORKSPACE, 'OEdata.draft.products.json'));
const reviewsPartial = readJson(join(WORKSPACE, 'OEdata.draft.reviews.json'));
const pagesPartial = readJson(join(WORKSPACE, 'OEdata.draft.pages.json'));
const blocksPartial = readJson(join(WORKSPACE, 'OEdata.draft.blocks.json'));
const formsPartial = readJson(join(WORKSPACE, 'OEdata.draft.forms.json'));
const menusPartial = readJson(join(WORKSPACE, 'OEdata.draft.menus.json'));
const attributeSetsPartial = readJson(
  join(WORKSPACE, 'OEdata.draft.attributeSets.json'),
);
const systemAttributesPartial = readJson(
  join(WORKSPACE, 'OEdata.draft.systemAttributes.json'),
);
const eventsPartial = readJson(join(WORKSPACE, 'OEdata.draft.events.json'));
const userPartial = readJson(join(WORKSPACE, 'OEdata.draft.user.json'));
const ordersPartial = readJson(join(WORKSPACE, 'OEdata.draft.orders.json'));
const miscClientPartial = readJson(
  join(WORKSPACE, 'OEdata.draft.miscClient.json'),
);
const indexPartial = readJson(join(WORKSPACE, 'OEdata.draft.index.json'));

// ---------------------------------------------------------------------------
// Step 2: bundle the rich product source via esbuild + write inline JSON.
// ---------------------------------------------------------------------------

console.log('[oedata] bundling rich product files…');

// Esbuild plugin: stub heavy peer modules (React, Next, lucide-react, contexts,
// utility components). The rich product source only relies on them at the
// type level; runtime emits plain product arrays.
const stubPlugin = {
  name: 'oedata-stub-imports',
  setup(b) {
    // Stub modules: anything that isn't .ts/.tsx data.
    b.onResolve({ filter: /^(react|react-dom|next\/.+|lucide-react|@.+)/ }, (args) => ({
      path: args.path,
      namespace: 'oedata-stub',
    }));
    b.onResolve(
      { filter: /(ProductCard|colorNames|colorUtils|colors|timings|Catalog|Wishlist|QuickView)/ },
      (args) => ({ path: args.path, namespace: 'oedata-stub' }),
    );
    // Static asset imports (images, css) → empty stubs.
    b.onResolve({ filter: /\.(png|jpe?g|svg|gif|webp|css|scss)$/ }, (args) => ({
      path: args.path,
      namespace: 'oedata-stub',
    }));
    b.onLoad({ filter: /.*/, namespace: 'oedata-stub' }, () => ({
      contents: 'export default {}; export const __OEdataStub = true;',
      loader: 'js',
    }));
  },
};

const richEntry = `
import { WOMEN_CLOTHING_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'women-clothing.ts'))};
import { WOMEN_BAGS_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'women-bags.ts'))};
import { WOMEN_SHOES_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'women-shoes.ts'))};
import { WOMEN_ACCESSORIES_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'women-accessories.ts'))};
import { MEN_CLOTHING_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'men-clothing.ts'))};
import { MEN_BAGS_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'men-bags.ts'))};
import { MEN_SHOES_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'men-shoes.ts'))};
import { MEN_ACCESSORIES_PRODUCTS } from ${JSON.stringify(join(DATA_DIR, 'men-accessories.ts'))};
import { SEO } from ${JSON.stringify(join(DATA_DIR, 'seoData.ts'))};
import { INFO_PAGE_META } from ${JSON.stringify(join(DATA_DIR, 'infoPages.ts'))};
import {
  BEST_SELLERS,
  NEW_ARRIVALS_PAGE_PRODUCTS,
  SALE_PAGE_PRODUCTS,
  FAVORITES_TRENDING,
  FAVORITES_RECOMMENDED,
} from ${JSON.stringify(join(DATA_DIR, 'homepageProducts.ts'))};
export default {
  wc: WOMEN_CLOTHING_PRODUCTS,
  wb: WOMEN_BAGS_PRODUCTS,
  ws: WOMEN_SHOES_PRODUCTS,
  wa: WOMEN_ACCESSORIES_PRODUCTS,
  mc: MEN_CLOTHING_PRODUCTS,
  mb: MEN_BAGS_PRODUCTS,
  ms: MEN_SHOES_PRODUCTS,
  ma: MEN_ACCESSORIES_PRODUCTS,
  SEO,
  INFO_PAGE_META,
  HOMEPAGE: {
    best_sellers_carousel: BEST_SELLERS,
    new_arrivals_carousel: NEW_ARRIVALS_PAGE_PRODUCTS,
    sale_carousel: SALE_PAGE_PRODUCTS,
    trending_products_block: FAVORITES_TRENDING,
    favorites_recommended_block: FAVORITES_RECOMMENDED,
  },
};
`;

const bundle = await esbuild({
  stdin: {
    contents: richEntry,
    loader: 'ts',
    resolveDir: REPO_ROOT,
  },
  bundle: true,
  write: false,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  plugins: [stubPlugin],
  logLevel: 'silent',
});

const bundleSrc = bundle.outputFiles[0].text;
// Evaluate bundle as a data-URL ESM module in this Node process.
const dataUrl = `data:text/javascript;base64,${Buffer.from(bundleSrc).toString('base64')}`;
const bundled = (await import(dataUrl)).default;

const {
  SEO: RICH_SEO,
  INFO_PAGE_META: RICH_INFO_META,
  HOMEPAGE: RICH_HOMEPAGE,
  ...RICH_BY_PREFIX
} = bundled; // { wc, wb, ws, wa, mc, mb, ms, ma }
const RICH_BY_ID = {};
for (const arr of Object.values(RICH_BY_PREFIX))
  for (const p of arr) RICH_BY_ID[p.id] = p;

console.log(
  `[oedata] bundled rich products: ${Object.values(RICH_BY_PREFIX).reduce((n, a) => n + a.length, 0)} entries`,
);

// ---------------------------------------------------------------------------
// Step 3: prepare clean output directory.
// ---------------------------------------------------------------------------

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

// ---------------------------------------------------------------------------
// Step 4: emit "static master" entities.
// ---------------------------------------------------------------------------

const stripMeta = (obj) => {
  if (Array.isArray(obj)) return obj.map(stripMeta);
  if (obj && typeof obj === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith('_')) continue;
      out[k] = stripMeta(v);
    }
    return out;
  }
  return obj;
};

writeTs('localeEntities.ts', {
  OE_LOCALE_ENTITIES: stripMeta(master.localeEntities),
  OE_DEFAULT_LOCALE: stripMeta(
    master.localeEntities.find((l) => l.isDefault) ?? master.localeEntities[0],
  ),
});

writeTs('currencies.ts', {
  OE_CURRENCIES: stripMeta(master.currencies),
  OE_DEFAULT_CURRENCY: stripMeta(
    master.currencies.find((c) => c.isDefault) ?? master.currencies[0],
  ),
});

writeTs('productStatuses.ts', { OE_PRODUCT_STATUSES: stripMeta(master.productStatuses) });
writeTs('userGroups.ts', { OE_USER_GROUPS: stripMeta(master.userGroups) });
writeTs('authProviders.ts', { OE_AUTH_PROVIDERS: stripMeta(master.authProviders) });
writeTs('paymentAccounts.ts', { OE_PAYMENT_ACCOUNTS: stripMeta(master.paymentAccounts) });
writeTs('deliveryMethods.ts', { OE_DELIVERY_METHODS: stripMeta(master.deliveryMethods) });

const promocodes = stripMeta(master.promocodes);
const promocodesByIdent = Object.fromEntries(promocodes.map((p) => [p.identifier, p]));
writeTs('promocodes.ts', {
  OE_PROMOCODES: promocodes,
  OE_PROMOCODES_BY_IDENTIFIER: promocodesByIdent,
});

writeTs('templatePreviews.ts', {
  OE_TEMPLATE_PREVIEWS: stripMeta(master.templatePreviews),
  OE_TEMPLATE_PREVIEWS_BY_MARKER: Object.fromEntries(
    stripMeta(master.templatePreviews).map((t) => [t.identifier, t]),
  ),
});

writeTs('templates.ts', { OE_TEMPLATES: stripMeta(master.templates) });
writeTs('productRelationsTemplates.ts', {
  OE_PRODUCT_RELATIONS_TEMPLATES: stripMeta(master.productRelationsTemplates),
});

// ---------------------------------------------------------------------------
// Step 5: emit attributeSets, systemAttributes.
// ---------------------------------------------------------------------------

const attributeSets = stripMeta(attributeSetsPartial.attributeSets);
writeTs('attributeSets.ts', {
  OE_ATTRIBUTE_SETS: attributeSets,
  OE_ATTRIBUTE_SETS_BY_MARKER: Object.fromEntries(
    attributeSets.map((a) => [a.identifier, a]),
  ),
});

const systemAttributes = stripMeta(systemAttributesPartial.systemAttributes);
writeTs('systemAttributes.ts', {
  OE_SYSTEM_ATTRIBUTES: systemAttributes,
  OE_SYSTEM_ATTRIBUTES_BY_MARKER: Object.fromEntries(
    systemAttributes.map((a) => [a.marker, a]),
  ),
});

// ---------------------------------------------------------------------------
// Step 6: emit events.
// ---------------------------------------------------------------------------

const events = stripMeta(eventsPartial.events);
writeTs('events.ts', {
  OE_EVENTS: events,
  OE_EVENTS_BY_IDENTIFIER: Object.fromEntries(events.map((e) => [e.identifier, e])),
});

// ---------------------------------------------------------------------------
// Step 7: emit user, orders.
// ---------------------------------------------------------------------------

writeTs('user.ts', { OE_USER: stripMeta(userPartial.user) });

writeTs('orders.ts', {
  OE_ORDER_STATUSES: stripMeta(ordersPartial.orderStatuses),
  OE_ORDERS_STORAGE: stripMeta(ordersPartial.ordersStorage),
  OE_ORDERS: stripMeta(ordersPartial.orders),
});

// ---------------------------------------------------------------------------
// Step 8: emit menus.
// ---------------------------------------------------------------------------

const menus = stripMeta(menusPartial.menus);
writeTs('menus.ts', {
  OE_MENUS: menus,
  OE_MENUS_BY_MARKER: Object.fromEntries(menus.map((m) => [m.identifier, m])),
});

// ---------------------------------------------------------------------------
// Step 9: emit forms (+ formsData from miscClient).
// ---------------------------------------------------------------------------

const forms = stripMeta(formsPartial.forms ?? []);
writeTs('forms.ts', {
  OE_FORMS: forms,
  OE_FORMS_BY_MARKER: Object.fromEntries(forms.map((f) => [f.identifier, f])),
});

writeTs('formsData.ts', { OE_FORMS_DATA: stripMeta(miscClientPartial.formsData) });

// ---------------------------------------------------------------------------
// Step 10: emit miscClient artifacts (stores, searchFacets, a11yStrings, userStateSchema).
// ---------------------------------------------------------------------------

writeTs('stores.ts', { OE_STORES: stripMeta(miscClientPartial.stores) });
writeTs('searchFacets.ts', {
  OE_SEARCH_FACETS: stripMeta(miscClientPartial.searchFacets),
});
writeTs('a11yStrings.ts', { OE_A11Y_STRINGS: stripMeta(miscClientPartial.a11yStrings) });

// userStateSchema: keep as-is (Record-of-arrays shape) — see README for rationale.
writeTs('userStateSchema.ts', {
  OE_USER_STATE_SCHEMA: stripMeta(miscClientPartial.userStateSchema),
});

// ---------------------------------------------------------------------------
// Step 11: build PRODUCTS — main heavy step.
// ---------------------------------------------------------------------------

console.log('[oedata] materializing products…');

const buildHint = productsPartial._buildHint;
const skuMapping = Object.fromEntries(
  buildHint.uniqueness.appliedMapping.map((m) => [m.originalId, m]),
);

// Status inference per Wave 7 audit.
const inferStatus = (p) => {
  if (p?.inStock === false) return 'out_of_stock';
  if (Array.isArray(p?.colorStock) && p.colorStock.length > 0) {
    if (p.colorStock.every((b) => !b)) return 'out_of_stock';
    if (p.colorStock.some((b) => !b)) return 'low_stock';
  }
  return 'in_stock';
};

const STATUS_TITLES = Object.fromEntries(
  master.productStatuses.map((s) => [s.identifier, s.localizeInfos.title]),
);

const PREVIEW_BY_MARKER = Object.fromEntries(
  master.templatePreviews.map((t) => [t.identifier, t.id]),
);

// Build entity-name → product entity-id map.
// id assignment: catalog products id = sequential 1.. by appliedMapping order.
let nextEntityId = 1;
const PRODUCT_ENTITY_ID = {}; // identifier (originalId) → numeric id

for (const m of buildHint.uniqueness.appliedMapping) {
  PRODUCT_ENTITY_ID[m.originalId] = nextEntityId++;
}

// Block id mapping (from blocks partial).
const BLOCK_ID_BY_IDENTIFIER = {};
for (const b of blocksPartial.blocks) BLOCK_ID_BY_IDENTIFIER[b.identifier] = b.id;

// Pre-compute reverse-relation indices from blocks (recommended_*, bundle_*, trending, recently_viewed).
const reverseIndex = {
  recommended: {}, // productId → entity[] (numeric ids of related products)
  bundle: {},
  trending: {},
  favorites_recommended: {},
  best_sellers: {},
  recently_viewed: {},
};

const productIdsForBlock = (block) => {
  const v = block.attributeValues?.products?.value;
  if (Array.isArray(v)) return v;
  return [];
};

// For "recommended_*" blocks (per pageUrl/category), each member product gets the
// other 5 ids as recommended_products entity[].
for (const block of blocksPartial.blocks) {
  if (
    block.relations_template_identifier === 'recommended' &&
    block.identifier?.startsWith('recommended_')
  ) {
    const members = productIdsForBlock(block);
    for (const id of members) {
      reverseIndex.recommended[id] ??= new Set();
      for (const other of members) {
        if (other !== id && PRODUCT_ENTITY_ID[other]) {
          reverseIndex.recommended[id].add(PRODUCT_ENTITY_ID[other]);
        }
      }
    }
  }
  if (block.relations_template_identifier === 'bundle') {
    const members = productIdsForBlock(block);
    for (const id of members) {
      reverseIndex.bundle[id] ??= new Set();
      for (const other of members) {
        if (other !== id && PRODUCT_ENTITY_ID[other]) {
          reverseIndex.bundle[id].add(PRODUCT_ENTITY_ID[other]);
        }
      }
    }
  }
  if (block.relations_template_identifier === 'trending') {
    const members = productIdsForBlock(block);
    for (const id of members) {
      reverseIndex.trending[id] ??= new Set();
      for (const other of members) {
        if (PRODUCT_ENTITY_ID[other]) {
          reverseIndex.trending[id].add(PRODUCT_ENTITY_ID[other]);
        }
      }
    }
  }
}

// Catalog → pageUrl mapping (per buildHint.byCatalog).
const PAGE_URL_BY_PREFIX = Object.fromEntries(
  Object.entries(buildHint.byCatalog).map(([prefix, info]) => [prefix, info.pageUrl]),
);

const buildProduct = (mapping, position) => {
  const orig = mapping.originalId;
  const id = PRODUCT_ENTITY_ID[orig];
  const rich = RICH_BY_ID[orig];
  const kind = mapping.kind; // 'catalog' | 'oos' | 'bundle'
  const prefix = orig.split('-')[0];
  const pageUrl = PAGE_URL_BY_PREFIX[prefix] ?? null;

  const isPhantomBundle = kind === 'bundle' && !rich;

  // Source resolution: rich object if found, otherwise build minimal phantom shell.
  const name =
    rich?.name ??
    (isPhantomBundle
      ? `Bundle Item — ${orig}`
      : kind === 'oos'
        ? `Out-of-Stock Item ${orig}`
        : orig);

  const status = isPhantomBundle ? 'in_stock' : inferStatus(rich);
  const templateIdentifier = isPhantomBundle ? 'bundle_only_product' : 'product_default';

  // ---- attributeValues ----
  const av = {};

  // cover
  if (rich?.image) {
    av.cover = {
      type: 'image',
      value: imageObject(rich.image),
      marker: 'cover',
      position: 1,
      isVisible: true,
      isProductPreview: true,
      previewTemplateId: PREVIEW_BY_MARKER.preview_product_card_3x4 ?? null,
      additionalFields: {},
    };
  } else if (isPhantomBundle) {
    av.cover = {
      type: 'image',
      value: imageObject('/placeholders/bundle-item.jpg'),
      marker: 'cover',
      position: 1,
      isVisible: true,
      isProductPreview: true,
      previewTemplateId: PREVIEW_BY_MARKER.preview_product_card_3x4 ?? null,
      additionalFields: {},
    };
  }

  // gallery
  if (Array.isArray(rich?.galleryImages) && rich.galleryImages.length) {
    av.gallery = {
      type: 'groupOfImages',
      value: rich.galleryImages.map((u) => imageObject(u)),
      marker: 'gallery',
      position: 2,
      isVisible: true,
      previewTemplateId: PREVIEW_BY_MARKER.preview_product_gallery_main_3x4 ?? null,
      additionalFields: {},
    };
  }

  // color images (variant)
  if (Array.isArray(rich?.colorImages) && rich.colorImages.length) {
    av.color_images = {
      type: 'groupOfImages',
      value: rich.colorImages.map((u) => imageObject(u)),
      marker: 'color_images',
      position: 3,
      isVisible: true,
      previewTemplateId: PREVIEW_BY_MARKER.preview_product_card_3x4 ?? null,
      additionalFields: {},
    };
  }

  // price (float; UI parses via parseFloat)
  if (rich?.price) {
    av.price = {
      type: 'float',
      value: parseFloat(String(rich.price).replace(/[^0-9.]/g, '')),
      marker: 'price',
      position: 4,
      isVisible: true,
      isPrice: true,
      additionalFields: { currency: { type: 'string', value: 'USD' } },
    };
  }

  // sale price (float)
  if (rich?.salePrice) {
    av.sale_price = {
      type: 'float',
      value: parseFloat(String(rich.salePrice).replace(/[^0-9.]/g, '')),
      marker: 'sale_price',
      position: 5,
      isVisible: true,
      isPrice: true,
      additionalFields: { currency: { type: 'string', value: 'USD' } },
    };
  }

  // F4: sibling currency attribute (validator §"Every isPrice → isCurrency adjacent")
  // Source: utils/formatPrice.ts:1 (USD `$`); single-currency project (currencies.ts).
  // Emitted on every product (visible only when at least one isPrice attribute is set).
  if (av.price || av.sale_price) {
    av.currency = {
      type: 'string',
      value: 'USD',
      marker: 'currency',
      position: 6,
      isVisible: false,
      isCurrency: true,
      additionalFields: {
        symbol: { type: 'string', value: '$' },
        source: { type: 'string', value: 'utils/formatPrice.ts:1' },
      },
    };
  }

  // brand → slug (rich value, not 'oneentry' fallback)
  if (rich?.brand) {
    av.brand = {
      type: 'radioButton',
      value: slugify(rich.brand),
      marker: 'brand',
      position: 6,
      isVisible: true,
      additionalFields: {},
    };
  }

  // colors (list of slugs; hex → slug). F3: marker `color` matches set_color attributeSet.
  if (Array.isArray(rich?.colors) && rich.colors.length) {
    av.color = {
      type: 'list',
      value: rich.colors.map(hexToSlug).filter(Boolean),
      marker: 'color',
      position: 7,
      isVisible: true,
      additionalFields: {},
    };
  }

  // sizes — F3: markers singularised to match attributeSet markers
  // (size_clothing → set_size_clothing; size_shoe_eu → set_size_shoe_eu).
  if (Array.isArray(rich?.sizes) && rich.sizes.length) {
    const clothingSizes = rich.sizes
      .filter(isClothingLetterSize)
      .map((s) => String(s).toLowerCase());
    const shoeSizes = rich.sizes.filter(isShoeNumericSize).map(String);
    if (clothingSizes.length) {
      av.size_clothing = {
        type: 'list',
        value: clothingSizes,
        marker: 'size_clothing',
        position: 8,
        isVisible: true,
        additionalFields: {},
      };
    }
    if (shoeSizes.length) {
      av.size_shoe_eu = {
        type: 'list',
        value: shoeSizes,
        marker: 'size_shoe_eu',
        position: 9,
        isVisible: true,
        additionalFields: {},
      };
    }
  }

  // label (BESTSELLER/NEW/SALE)
  if (rich?.label) {
    av.label = {
      type: 'radioButton',
      value: slugify(rich.label),
      marker: 'label',
      position: 10,
      isVisible: true,
      additionalFields: {},
    };
  }

  // sku + article (uniquified by oedata-31)
  av.sku = {
    type: 'string',
    value: mapping.sku,
    marker: 'sku',
    position: 11,
    isVisible: true,
    isSku: true,
    additionalFields: {},
  };
  av.article = {
    type: 'string',
    value: mapping.article,
    marker: 'article',
    position: 12,
    isVisible: true,
    additionalFields: {},
  };

  // taxonomy radioButton attributes
  const taxonomyMap = {
    season: rich?.season,
    material: rich?.material,
    style: rich?.style,
    fit: rich?.fit,
    clothing_type: rich?.clothingType,
    bag_type: rich?.bagType,
    shoe_type: rich?.shoeType,
    accessory_type: rich?.accessoryType,
  };
  let pos = 13;
  for (const [marker, raw] of Object.entries(taxonomyMap)) {
    if (raw) {
      av[marker] = {
        type: 'radioButton',
        value: slugify(raw),
        marker,
        position: pos,
        isVisible: true,
        additionalFields: {},
      };
    }
    pos++;
  }

  // specs json
  if (rich?.specs) {
    av.specs = {
      type: 'json',
      value: JSON.stringify(rich.specs),
      marker: 'specs',
      position: 21,
      isVisible: true,
      additionalFields: {},
    };
  }

  // entity reverse-references (recommended/bundle/trending/recently/reviews)
  const recommendedIds = Array.from(reverseIndex.recommended[orig] ?? []).slice(0, 6);
  const bundleIds = Array.from(reverseIndex.bundle[orig] ?? []);
  const trendingIds = Array.from(reverseIndex.trending[orig] ?? []);

  av.recommended_products = {
    type: 'entity',
    value: recommendedIds,
    marker: 'recommended_products',
    position: 32,
    isVisible: false,
    moduleIdentifier: 'content',
    additionalFields: {},
  };
  av.bundle_products = {
    type: 'entity',
    value: bundleIds,
    marker: 'bundle_products',
    position: 33,
    isVisible: false,
    moduleIdentifier: 'content',
    additionalFields: {},
  };
  av.trending_products = {
    type: 'entity',
    value: trendingIds,
    marker: 'trending_products',
    position: 34,
    isVisible: false,
    moduleIdentifier: 'content',
    additionalFields: {},
  };
  av.recently_viewed_products = {
    type: 'entity',
    value: [],
    marker: 'recently_viewed_products',
    position: 35,
    isVisible: false,
    moduleIdentifier: 'content',
    additionalFields: {},
  };

  // reviews entity[]: 5 numeric ids (filled in step 12 below; placeholder identifiers)
  // We resolve to numeric ids after building the review table.
  av.__reviews_placeholder = orig; // marker for postprocess

  return {
    id,
    identifier: orig,
    localizeInfos: {
      title: name,
      menuTitle: name,
      htmlContent: '',
      plainContent: '',
    },
    attributeValues: av,
    statusIdentifier: status,
    statusLocalizeInfos: { title: STATUS_TITLES[status] ?? status },
    templateIdentifier,
    position,
    version: 1,
    deleted: false,
    blocked: false,
    isVisible: true,
    previewImage:
      rich?.image ?? (isPhantomBundle ? '/placeholders/bundle-item.jpg' : ''),
    pageUrl,
  };
};

const products = buildHint.uniqueness.appliedMapping.map((m, i) =>
  buildProduct(m, i + 1),
);

// ---------------------------------------------------------------------------
// Step 12: build REVIEWS (108 products × 5 = 540).
// ---------------------------------------------------------------------------

console.log('[oedata] materializing reviews…');

let nextReviewId = 100000; // reserve a high range so reviews never collide with product ids
const reviews = [];
const reviewsByProduct = {}; // productEntityId → numeric review ids

for (const product of products) {
  const orig = product.identifier;
  const rich = RICH_BY_ID[orig];
  // Reviews are inline on rich.reviews. If absent (phantom bundles, OOS w/o reviews) — empty pool.
  const pool = Array.isArray(rich?.reviews) ? rich.reviews.slice(0, 5) : [];
  const targetCount = pool.length ? 5 : 0;
  reviewsByProduct[product.id] = [];

  for (let n = 1; n <= targetCount; n++) {
    const r = pool[(n - 1) % pool.length];
    const rid = nextReviewId++;
    const identifier = `${orig}-r${n}`;
    const review = {
      id: rid,
      identifier,
      localizeInfos: {
        title: r.title ?? '',
        menuTitle: r.title ?? '',
        htmlContent: '',
        plainContent: r.body ?? '',
      },
      attributeValues: {
        rating: {
          type: 'integer',
          value: Number(r.rating ?? 0),
          marker: 'rating',
          position: 1,
          isVisible: true,
          additionalFields: {},
        },
        headline: {
          type: 'string',
          value: r.title ?? '',
          marker: 'headline',
          position: 2,
          isVisible: true,
          additionalFields: {},
        },
        body: {
          type: 'text',
          value: richText(r.body ?? ''),
          marker: 'body',
          position: 3,
          isVisible: true,
          additionalFields: {},
        },
        author_name: {
          type: 'string',
          value: r.author ?? '',
          marker: 'author_name',
          position: 4,
          isVisible: true,
          additionalFields: {},
        },
        review_date: {
          type: 'date',
          value: {
            fullDate: r.date ? new Date(r.date).toISOString() : null,
            formattedValue: r.date ?? '',
            formatString: 'YYYY-MM-DD',
          },
          marker: 'review_date',
          position: 5,
          isVisible: true,
          additionalFields: {},
        },
        size: {
          type: 'string',
          value: r.size ?? null,
          marker: 'size',
          position: 6,
          isVisible: true,
          additionalFields: {},
        },
        verified: {
          type: 'radioButton',
          value: r.verified ? 'true' : 'false',
          marker: 'verified',
          position: 7,
          isVisible: true,
          additionalFields: {},
        },
        helpful_count: {
          type: 'integer',
          value: Number(r.helpful ?? 0),
          marker: 'helpful_count',
          position: 8,
          isVisible: true,
          additionalFields: {},
        },
        productId: {
          type: 'entity',
          value: product.id,
          marker: 'productId',
          position: 9,
          isVisible: false,
          moduleIdentifier: 'content',
          additionalFields: {},
        },
      },
      templateIdentifier: 'review_default',
      position: n,
      version: 1,
      deleted: false,
      blocked: false,
      isVisible: true,
    };
    reviews.push(review);
    reviewsByProduct[product.id].push(rid);
  }
}

// Backfill reviews entity attribute on products + remove placeholder.
for (const product of products) {
  const ids = reviewsByProduct[product.id] ?? [];
  product.attributeValues.reviews = {
    type: 'entity',
    value: ids,
    marker: 'reviews',
    position: 36,
    isVisible: false,
    moduleIdentifier: 'content',
    additionalFields: {},
  };
  delete product.attributeValues.__reviews_placeholder;
}

// ---------------------------------------------------------------------------
// Step 13: build OE_PRODUCTS_BY_PAGE_URL.
// ---------------------------------------------------------------------------

const productsByPageUrl = {};
for (const p of products) {
  if (!p.pageUrl) continue;
  productsByPageUrl[p.pageUrl] ??= [];
  productsByPageUrl[p.pageUrl].push(p.id);
}

writeTs('products.ts', {
  OE_PRODUCTS: products,
  OE_PRODUCTS_BY_PAGE_URL: productsByPageUrl,
});

writeTs('reviews.ts', {
  OE_REVIEWS: reviews,
  OE_REVIEWS_BY_PRODUCT_ID: reviewsByProduct,
});

console.log(
  `[oedata] products: ${products.length} (${products.filter((p) => p.templateIdentifier === 'bundle_only_product').length} bundle-only); reviews: ${reviews.length}`,
);

// ---------------------------------------------------------------------------
// Step 14: BLOCKS — resolve product identifier strings → numeric entity ids.
// F2 (Wave 7.6): resolve "<derived from XXX>" string placeholders for the 5
// homepage/favorites carousels via the rich homepageProducts.ts source.
// F3 (Wave 7.6): inject inline listTitles for 11 inline-list block attributes
// without listTitles (validator §"Every categorical inline list → listTitles").
// F5 (Wave 7.6): inject `cookie_banner` stub block on global page (validator
// §"global-page contains header/footer/cookie/mobile-nav").
// ---------------------------------------------------------------------------

console.log('[oedata] materializing blocks…');

// Map block.identifier → list of originalIds to resolve from the rich source.
const HOMEPAGE_BLOCK_TO_RICH_KEY = {
  best_sellers_carousel: 'best_sellers_carousel',
  new_arrivals_carousel: 'new_arrivals_carousel',
  sale_carousel: 'sale_carousel',
  trending_products_block: 'trending_products_block',
  favorites_recommended_block: 'favorites_recommended_block',
};

const resolveHomepageBlockProducts = (blockIdentifier) => {
  const key = HOMEPAGE_BLOCK_TO_RICH_KEY[blockIdentifier];
  if (!key) return null;
  const arr = RICH_HOMEPAGE?.[key];
  if (!Array.isArray(arr)) return null;
  return arr
    .map((p) => PRODUCT_ENTITY_ID[p?.id])
    .filter((n) => typeof n === 'number');
};

const resolveBlockProductRefs = (val, blockIdentifier) => {
  if (Array.isArray(val)) {
    return val.map((id) => PRODUCT_ENTITY_ID[id] ?? id);
  }
  if (typeof val === 'string') {
    // F2: resolve "<derived from …>" placeholders via homepageProducts.ts.
    const homepageIds = resolveHomepageBlockProducts(blockIdentifier);
    if (homepageIds) return homepageIds;
  }
  return val;
};

// F3: build inline listTitles for known categorical inline-list block attributes.
// Each entry maps `${blockIdentifier}/${marker}` → human-readable titles array,
// derived strictly from the source values present in the workspace partial.
// Source for human titles: 07-hardcoded-strings.md / 11-locales-i18n.md / UI labels.
const HUMANIZE = (slug) =>
  String(slug)
    .split('_')
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');

const buildInlineListTitles = (values) =>
  Array.isArray(values)
    ? values.map((v, i) => ({
        title: HUMANIZE(v),
        value: String(v),
        position: i + 1,
      }))
    : null;

let blocksWithInlineListTitles = 0;
let homepageBlocksResolved = 0;

const blocks = blocksPartial.blocks.map((b) => {
  const cleaned = stripMeta(b);
  // Resolve products[].value (entity refs) — F2.
  const productsAv = cleaned.attributeValues?.products;
  if (productsAv && productsAv.value !== undefined) {
    const before = productsAv.value;
    productsAv.value = resolveBlockProductRefs(before, cleaned.identifier);
    if (typeof before === 'string' && Array.isArray(productsAv.value)) {
      homepageBlocksResolved++;
    }
  }
  // F3: inject inline listTitles for any list/radioButton without listTitles.
  for (const [marker, av] of Object.entries(cleaned.attributeValues || {})) {
    if (
      av &&
      (av.type === 'list' || av.type === 'radioButton') &&
      !av.listTitles &&
      Array.isArray(av.value)
    ) {
      av.listTitles = buildInlineListTitles(av.value);
      blocksWithInlineListTitles++;
    }
  }
  return cleaned;
});

console.log(
  `[oedata] homepage blocks resolved (F2): ${homepageBlocksResolved}; inline listTitles injected (F3): ${blocksWithInlineListTitles}`,
);

// F5: add `cookie_banner` stub block on global page documenting the
// deliberate non-implementation in source (Q-COOKIE-BANNER, 28-unsourced.md).
// Per §1 hard rules — we never invent UI content; this stub carries
// `is_implemented=false` + a placeholder message to make the gap explicit.
const COOKIE_BANNER_BLOCK_ID = (blocks.length
  ? Math.max(...blocks.map((b) => b.id ?? 0))
  : 0) + 1;

const cookieBannerBlock = {
  id: COOKIE_BANNER_BLOCK_ID,
  identifier: 'cookie_banner',
  pageUrl: 'global',
  general_type_id: 18,
  templateIdentifier: 'common_block',
  position: 9000,
  isVisible: false,
  localizeInfos: {
    title: 'Cookie banner (not implemented in source)',
    menuTitle: '',
    htmlContent: '',
    plainContent: '',
  },
  attributeValues: {
    is_implemented: {
      type: 'string',
      value: 'false',
      marker: 'is_implemented',
      position: 1,
      isVisible: false,
      additionalFields: {},
    },
    placeholder_message: {
      type: 'string',
      value: 'Cookie banner not yet implemented in source project',
      marker: 'placeholder_message',
      position: 2,
      isVisible: false,
      additionalFields: {
        source: { type: 'string', value: '28-unsourced.md#Q-COOKIE-BANNER' },
      },
    },
  },
};
blocks.push(cookieBannerBlock);

const blocksByPageUrl = {};
for (const b of blocks) {
  if (!b.pageUrl) continue;
  blocksByPageUrl[b.pageUrl] ??= [];
  blocksByPageUrl[b.pageUrl].push(b);
}
const blocksByMarker = Object.fromEntries(blocks.map((b) => [b.identifier, b]));

writeTs('blocks.ts', {
  OE_BLOCKS: blocks,
  OE_BLOCKS_BY_PAGE_URL: blocksByPageUrl,
  OE_BLOCKS_BY_MARKER: blocksByMarker,
});

// ---------------------------------------------------------------------------
// Step 15: PAGES — keep all SEO/attributeValues, resolve any product refs,
//                  resolve global blocks_* placeholders (F1),
//                  inject meta_description from seoData.ts / infoPages.ts (F2).
// ---------------------------------------------------------------------------

console.log('[oedata] materializing pages…');

const PAGE_PRODUCTS_BY_KEY = {
  '<all_wc_product_ids>': 'women/clothing',
  '<all_ws_product_ids>': 'women/shoes',
  '<all_wb_product_ids>': 'women/bags',
  '<all_wa_product_ids>': 'women/accessories',
  '<all_mc_product_ids>': 'men/clothing',
  '<all_ms_product_ids>': 'men/shoes',
  '<all_mb_product_ids>': 'men/bags',
  '<all_ma_product_ids>': 'men/accessories',
};

const resolvePagePlaceholder = (raw) => {
  if (typeof raw !== 'string') return raw;
  const url = PAGE_PRODUCTS_BY_KEY[raw];
  if (url) return productsByPageUrl[url] ?? [];
  return raw;
};

// --- F1: resolve global page header/footer/mobile_nav block ids -----------
//
// `blocks` (Step 14 above) carries the canonical numeric ids for every
// header_*/accessibility_*/footer_*/mobile_nav_*/mobile_footer_* block
// scoped to pageUrl="global". These are the entity ids the global page
// should reference instead of the literal string placeholders that the
// schema-builder draft emits (`"<entity_ids_for_header_blocks>"` etc).
//
// Per .claude/rules/oedata/01-hard-rules.md §1, we never invent ids — they
// are derived strictly from the blocks partial.

const GLOBAL_BLOCKS = blocks.filter((b) => b.pageUrl === 'global');
const HEADER_BLOCK_IDS = GLOBAL_BLOCKS.filter(
  (b) =>
    typeof b.identifier === 'string' &&
    (b.identifier.startsWith('header_') ||
      b.identifier === 'accessibility_skip_link'),
)
  .sort((a, b) => (a.position ?? 0) - (b.position ?? 0))
  .map((b) => b.id);

const FOOTER_BLOCK_IDS = GLOBAL_BLOCKS.filter(
  (b) => typeof b.identifier === 'string' && b.identifier.startsWith('footer_'),
)
  .sort((a, b) => (a.position ?? 0) - (b.position ?? 0))
  .map((b) => b.id);

const MOBILE_NAV_BLOCK_IDS = GLOBAL_BLOCKS.filter(
  (b) =>
    typeof b.identifier === 'string' &&
    (b.identifier.startsWith('mobile_nav_') ||
      b.identifier.startsWith('mobile_footer_')),
)
  .sort((a, b) => (a.position ?? 0) - (b.position ?? 0))
  .map((b) => b.id);

const GLOBAL_BLOCK_PLACEHOLDERS = {
  '<entity_ids_for_header_blocks>': HEADER_BLOCK_IDS,
  '<entity_ids_for_footer_blocks>': FOOTER_BLOCK_IDS,
  '<entity_ids_for_mobile_blocks>': MOBILE_NAV_BLOCK_IDS,
  '<entity_ids_for_mobile_nav_blocks>': MOBILE_NAV_BLOCK_IDS,
};

const resolveGlobalBlocksPlaceholder = (raw) => {
  if (typeof raw !== 'string') return raw;
  if (raw in GLOBAL_BLOCK_PLACEHOLDERS) return GLOBAL_BLOCK_PLACEHOLDERS[raw];
  return raw;
};

// --- F2: build pageUrl → meta description map ----------------------------
//
// Sources (in priority order):
//   1. seoData.ts → SEO[<seoKey>].description
//   2. infoPages.ts → INFO_PAGE_META[<slug>].description
// Pages where neither source applies (private/checkout/noindex specific to
// no-source slots, error pages, structural shells) → empty value with
// additionalFields.source = "unsourced" so downstream tools can treat them
// as deliberately blank rather than missing.

const PAGE_URL_TO_SEO_KEY = {
  home: 'home',
  'women/clothing': 'womenClothing',
  'women/shoes': 'womenShoes',
  'women/bags': 'womenBags',
  'women/accessories': 'womenAccessories',
  'men/clothing': 'menClothing',
  'men/shoes': 'menShoes',
  'men/bags': 'menBags',
  'men/accessories': 'menAccessories',
  sale: 'sale',
  new: 'newArrivals',
  stores: 'stores',
  cart: 'cart',
  favorites: 'favorites',
  account: 'account',
  'checkout/delivery': 'checkoutDelivery',
  'checkout/payment': 'checkoutPayment',
  'checkout/confirmation': 'checkoutConfirmation',
  'download/filter-system': 'filterSystemDownload',
};

let metaDescResolvedFromSEO = 0;
let metaDescResolvedFromInfo = 0;
let metaDescUnsourced = 0;
let metaDescAlreadyPresent = 0;

let metaTitleResolvedFromSEO = 0;
let metaTitleResolvedFromInfo = 0;
let metaTitleResolvedFromLocalize = 0;
let metaTitleUnsourced = 0;
let metaTitleAlreadyPresent = 0;

const resolveMetaDescription = (page) => {
  // 1. Page already has meta_description from the draft → respect it.
  if (page.attributeValues?.meta_description !== undefined) {
    metaDescAlreadyPresent++;
    return null;
  }

  const url = page.pageUrl;
  // 2. seoData.ts (catalog/sale/checkout/account/etc).
  const seoKey = PAGE_URL_TO_SEO_KEY[url];
  if (seoKey && RICH_SEO?.[seoKey]?.description) {
    metaDescResolvedFromSEO++;
    return { value: String(RICH_SEO[seoKey].description), source: 'seoData.ts' };
  }
  // 3. infoPages.ts (about-us, faq, terms, etc — keyed by slug = pageUrl).
  if (url && RICH_INFO_META?.[url]?.description) {
    metaDescResolvedFromInfo++;
    return { value: String(RICH_INFO_META[url].description), source: 'infoPages.ts' };
  }
  // 4. No source — emit unsourced placeholder (empty string + tag).
  metaDescUnsourced++;
  return { value: '', source: 'unsourced' };
};

const buildMetaDescriptionAttr = (resolved, position) => ({
  type: 'string',
  value: resolved.value,
  marker: 'meta_description',
  position,
  isVisible: false,
  additionalFields: {
    source: { type: 'string', value: resolved.source },
  },
});

// F6: meta_title resolution per validator §"Every page — meta_title".
// Sources (priority):
//   1. attributeValues.meta_title already present → respect.
//   2. seoData.ts → SEO[<seoKey>].title.
//   3. infoPages.ts → INFO_PAGE_META[<slug>].title.
//   4. Page localizeInfos.title (always present on every page).
//   5. Otherwise unsourced placeholder ('' + source='unsourced').
const resolveMetaTitle = (page) => {
  if (page.attributeValues?.meta_title !== undefined) {
    metaTitleAlreadyPresent++;
    return null;
  }
  const url = page.pageUrl;
  const seoKey = PAGE_URL_TO_SEO_KEY[url];
  if (seoKey && RICH_SEO?.[seoKey]?.title) {
    metaTitleResolvedFromSEO++;
    return { value: String(RICH_SEO[seoKey].title), source: 'seoData.ts' };
  }
  if (url && RICH_INFO_META?.[url]?.title) {
    metaTitleResolvedFromInfo++;
    return { value: String(RICH_INFO_META[url].title), source: 'infoPages.ts' };
  }
  const localizeTitle = page.localizeInfos?.title;
  if (typeof localizeTitle === 'string' && localizeTitle.length) {
    metaTitleResolvedFromLocalize++;
    return { value: localizeTitle, source: 'localizeInfos.title' };
  }
  metaTitleUnsourced++;
  return { value: '', source: 'unsourced' };
};

const buildMetaTitleAttr = (resolved, position) => ({
  type: 'string',
  value: resolved.value,
  marker: 'meta_title',
  position,
  isVisible: false,
  additionalFields: {
    source: { type: 'string', value: resolved.source },
  },
});

const pages = pagesPartial.pages.map((p) => {
  const cleaned = stripMeta(p);
  cleaned.attributeValues = cleaned.attributeValues || {};

  // F1: resolve products + global blocks_* placeholders.
  if (cleaned.attributeValues.products?.value !== undefined) {
    cleaned.attributeValues.products.value = resolvePagePlaceholder(
      cleaned.attributeValues.products.value,
    );
  }
  for (const marker of ['blocks_header', 'blocks_footer', 'blocks_mobile_nav']) {
    const av = cleaned.attributeValues[marker];
    if (av && av.value !== undefined) {
      av.value = resolveGlobalBlocksPlaceholder(av.value);
    }
  }

  // F2: ensure meta_description on every page.
  const resolvedDesc = resolveMetaDescription(cleaned);
  if (resolvedDesc !== null) {
    const usedPositions = new Set(
      Object.values(cleaned.attributeValues).map((a) => a?.position).filter((n) => typeof n === 'number'),
    );
    let pos = 2;
    while (usedPositions.has(pos)) pos++;
    cleaned.attributeValues.meta_description = buildMetaDescriptionAttr(
      resolvedDesc,
      pos,
    );
  }

  // F6: ensure meta_title on every page.
  const resolvedTitle = resolveMetaTitle(cleaned);
  if (resolvedTitle !== null) {
    const usedPositions = new Set(
      Object.values(cleaned.attributeValues).map((a) => a?.position).filter((n) => typeof n === 'number'),
    );
    let pos = 1;
    while (usedPositions.has(pos)) pos++;
    cleaned.attributeValues.meta_title = buildMetaTitleAttr(
      resolvedTitle,
      pos,
    );
  }

  // F3: inject inline listTitles for any list/radioButton attribute on this
  // page that lacks them (validator §"Every categorical inline → listTitles").
  for (const [, av] of Object.entries(cleaned.attributeValues || {})) {
    if (
      av &&
      (av.type === 'list' || av.type === 'radioButton') &&
      !av.listTitles &&
      Array.isArray(av.value)
    ) {
      av.listTitles = buildInlineListTitles(av.value);
    }
  }

  return cleaned;
});

console.log(
  `[oedata] meta_description: from seoData=${metaDescResolvedFromSEO}, from infoPages=${metaDescResolvedFromInfo}, unsourced=${metaDescUnsourced}, already-present(skipped)=${metaDescAlreadyPresent}`,
);
console.log(
  `[oedata] meta_title: from seoData=${metaTitleResolvedFromSEO}, from infoPages=${metaTitleResolvedFromInfo}, from localizeInfos=${metaTitleResolvedFromLocalize}, unsourced=${metaTitleUnsourced}, already-present(skipped)=${metaTitleAlreadyPresent}`,
);
console.log(
  `[oedata] global blocks resolved: header=${HEADER_BLOCK_IDS.length}, footer=${FOOTER_BLOCK_IDS.length}, mobile_nav=${MOBILE_NAV_BLOCK_IDS.length}`,
);

const pagesByUrl = Object.fromEntries(pages.map((p) => [p.pageUrl, p]));

writeTs('pages.ts', { OE_PAGES: pages, OE_PAGES_BY_URL: pagesByUrl });

// ---------------------------------------------------------------------------
// Step 16: emit index.ts (use template from index partial verbatim).
// ---------------------------------------------------------------------------

console.log('[oedata] writing index.ts…');

writeFileSync(
  join(OUT_DIR, 'index.ts'),
  BANNER + indexPartial.indexTsContent,
  'utf8',
);

// ---------------------------------------------------------------------------
// Step 17: README.md.
// ---------------------------------------------------------------------------

const readme = `# OEdata

Auto-generated by \`scripts/build-oedata.mjs\` (session v2, Wave 7.3).

**Reproducibility hash:** \`${REPRO_HASH}\`

## Regenerate

\`\`\`bash
node scripts/build-oedata.mjs
\`\`\`

The script is fully idempotent — re-running on the same workspace produces
byte-identical TypeScript files (key sorting + no timestamps).

## Inputs

- \`.oedata-workspace/OEdata.draft.json\` (master)
- \`.oedata-workspace/OEdata.draft.<domain>.json\` × 12 partials
- \`src/app/data/{women,men}-{clothing,bags,shoes,accessories}.ts\` (rich product source, bundled via esbuild with type-only stubs)

## Counts (this materialization)

- Products: ${products.length} (${products.filter((p) => p.templateIdentifier === 'product_default').length} catalog+oos via \`product_default\` + ${products.filter((p) => p.templateIdentifier === 'bundle_only_product').length} phantom bundle-only)
- Reviews: ${reviews.length} (every product with a non-empty \`reviews\` pool in the rich source emits 5 review entities; phantom bundles emit none)
- Pages: ${pages.length}
- Blocks: ${blocks.length}
- Forms: ${forms.length}
- Menus: ${menus.length}
- AttributeSets: ${attributeSets.length}
- SystemAttributes: ${systemAttributes.length}
- Events: ${events.length}

## Known source inconsistencies (recorded; preserved as-is)

- **D9 (currency):** \`seoData.ts\` declares \`GBP\` (\`systemAttributes.currency = "GBP"\`), but the
  UI uses USD \`$\` everywhere (\`utils/formatPrice.ts\`, all rich product price strings).
  Per §1.1 (UI authoritative on conflict), \`OE_DEFAULT_CURRENCY\` is USD; the GBP entry
  is preserved with \`isActive: false\`.
- **D11+D17 (stores schema mismatch):** \`stores.ts\` (mock) and \`store_schema_defaults\` (system attribute,
  \`currenciesAccepted: GBP\`) declare GBP for store JSON-LD; UI checkout uses USD. Both are emitted as-is.
- **D12 (logo):** \`headerConfig.ts:15\` and \`Footer.tsx:125\` both reference \`ONEENTRY FASHION\` as the
  logo alt text — this is captured as \`systemAttributes.site_logo_alt\`. The actual logo image asset is
  rendered as inline SVG and is intentionally NOT materialized as an OEdata image entity (no \`/logo.svg\`
  file exists in \`public/\`).
- **SYS-2 / SYS-3:** \`systemAttributes\` rows 44 (\`metadata_route_llms_txt\`) and 46 (\`metadata_route_icon_svg\`)
  reference Next.js conventional metadata-route slots whose source files are NOT present in the project.
  The route paths are emitted; \`_unsourced\` flags are dropped from the final TS but documented in
  \`.oedata-workspace/28-unsourced.md\`.
- **V-AHO-2 (anti-hallucination):** all entity-attribute reverse references on Products
  (\`recommended_products\`, \`bundle_products\`, \`trending_products\`) are derived strictly from the
  blocks partial — never invented. Empty arrays where no inversion exists.
- **Q-MCP-* (9 outstanding MCP questions):** see \`.oedata-workspace/31-open-questions.md\`. None block
  materialization; all defaults come from cached MCP rules.

## userStateSchema shape note

\`OE_USER_STATE_SCHEMA\` is emitted as a Record-of-arrays (\`{ persistedKeys: [], transientKeys: [] }\`)
mirroring the workspace partial. This is intentional — it makes per-key shape descriptions discoverable
without losing the \`_source\` / \`_note\` annotations from the audit. Consumers that want a flat
list can derive it via \`[...OE_USER_STATE_SCHEMA.persistedKeys, ...OE_USER_STATE_SCHEMA.transientKeys]\`.

## Cache reference

\`.oedata-workspace/cache/mcp/index.json\` — every type/flag emitted in OEdata is backed by a
cached MCP rule snapshot at session-build time.
`;

writeFileSync(join(OUT_DIR, 'README.md'), readme, 'utf8');

console.log(`[oedata] done — wrote ${OUT_DIR}`);
